import type {
  ActivityItem,
  Invoice,
  RecoveryMonth,
  SequenceStep,
  SequenceTemplate,
} from "./types";

export const DEFAULT_SEQUENCE_STEPS: SequenceStep[] = [
  { id: "s1", day: 3, channel: "email", label: "Friendly reminder", enabled: true },
  { id: "s2", day: 7, channel: "email+sms", label: "Follow-up + SMS", enabled: true },
  { id: "s3", day: 14, channel: "email", label: "Firm notice", enabled: true },
  { id: "s4", day: 30, channel: "email", label: "Escalation notice", enabled: true },
];

export const SEQUENCE_TEMPLATES: SequenceTemplate[] = [
  {
    id: "default",
    name: "Standard 30-day chase",
    description: "Email day 3, email+SMS day 7, firm email day 14, escalation day 30",
    steps: DEFAULT_SEQUENCE_STEPS,
    tone: "friendly",
    activeInvoices: 12,
  },
  {
    id: "gentle",
    name: "Gentle freelancer",
    description: "Softer cadence for long-term clients you want to keep",
    steps: [
      { id: "g1", day: 5, channel: "email", label: "Soft check-in", enabled: true },
      { id: "g2", day: 12, channel: "email", label: "Second reminder", enabled: true },
      { id: "g3", day: 21, channel: "email+sms", label: "Polite urgency", enabled: true },
      { id: "g4", day: 35, channel: "email", label: "Final notice", enabled: true },
    ],
    tone: "friendly",
    activeInvoices: 4,
  },
  {
    id: "firm",
    name: "Firm B2B",
    description: "Shorter timeline for corporate accounts with NET-30 terms",
    steps: [
      { id: "f1", day: 1, channel: "email", label: "Due date reminder", enabled: true },
      { id: "f2", day: 5, channel: "email+sms", label: "Past due notice", enabled: true },
      { id: "f3", day: 10, channel: "email", label: "Collections warning", enabled: true },
      { id: "f4", day: 20, channel: "email", label: "Final escalation", enabled: true },
    ],
    tone: "formal",
    activeInvoices: 6,
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: "inv-001",
    number: "INV-2026-0412",
    client: "Sarah Chen",
    company: "Brightline Design Co.",
    email: "sarah@brightlinedesign.com",
    phone: "+1 (415) 555-0182",
    amount: 4250.0,
    dueDate: "2026-06-28",
    issuedDate: "2026-06-14",
    status: "overdue",
    sequenceStep: 3,
    lastContact: "2026-07-10",
    tone: "firm",
    integration: "quickbooks",
    daysOverdue: 15,
  },
  {
    id: "inv-002",
    number: "INV-2026-0398",
    client: "Marcus Williams",
    company: "Williams Plumbing LLC",
    email: "marcus@williamsplumbing.com",
    phone: "+1 (512) 555-0294",
    amount: 1875.5,
    dueDate: "2026-07-05",
    issuedDate: "2026-06-21",
    status: "active",
    sequenceStep: 2,
    lastContact: "2026-07-08",
    tone: "friendly",
    integration: "freshbooks",
    daysOverdue: 8,
  },
  {
    id: "inv-003",
    number: "INV-2026-0421",
    client: "Elena Rodriguez",
    company: "Rodriguez Legal Services",
    email: "elena@rodriguezlegal.com",
    phone: "+1 (305) 555-0371",
    amount: 6200.0,
    dueDate: "2026-07-01",
    issuedDate: "2026-06-17",
    status: "overdue",
    sequenceStep: 4,
    lastContact: "2026-07-11",
    tone: "formal",
    integration: "quickbooks",
    daysOverdue: 12,
  },
  {
    id: "inv-004",
    number: "INV-2026-0387",
    client: "James Okonkwo",
    company: "Okonkwo Consulting",
    email: "james@okonkwoconsulting.io",
    phone: "+1 (646) 555-0448",
    amount: 3400.0,
    dueDate: "2026-07-15",
    issuedDate: "2026-07-01",
    status: "active",
    sequenceStep: 1,
    lastContact: "2026-07-04",
    tone: "friendly",
    integration: "wave",
    daysOverdue: 0,
  },
  {
    id: "inv-005",
    number: "INV-2026-0355",
    client: "Amy Nakamura",
    company: "Nakamura Photography",
    email: "amy@nakamuraphoto.com",
    phone: "+1 (206) 555-0512",
    amount: 950.0,
    dueDate: "2026-06-20",
    issuedDate: "2026-06-06",
    status: "overdue",
    sequenceStep: 3,
    lastContact: "2026-07-09",
    tone: "firm",
    integration: "csv",
    daysOverdue: 23,
  },
  {
    id: "inv-006",
    number: "INV-2026-0433",
    client: "David Park",
    company: "Park & Associates CPA",
    email: "dpark@parkassociates.com",
    phone: "+1 (312) 555-0627",
    amount: 5100.0,
    dueDate: "2026-07-20",
    issuedDate: "2026-07-06",
    status: "active",
    sequenceStep: 0,
    lastContact: "—",
    tone: "formal",
    integration: "quickbooks",
    daysOverdue: 0,
  },
  {
    id: "inv-007",
    number: "INV-2026-0341",
    client: "Lisa Thompson",
    company: "Thompson Event Planning",
    email: "lisa@thompsonevents.com",
    phone: "+1 (404) 555-0733",
    amount: 2800.0,
    dueDate: "2026-06-15",
    issuedDate: "2026-06-01",
    status: "paused",
    sequenceStep: 2,
    lastContact: "2026-07-06",
    tone: "friendly",
    integration: "freshbooks",
    daysOverdue: 28,
  },
  {
    id: "inv-008",
    number: "INV-2026-0440",
    client: "Robert Hayes",
    company: "Hayes Construction Group",
    email: "rhayes@hayesconstruction.com",
    phone: "+1 (713) 555-0841",
    amount: 12400.0,
    dueDate: "2026-07-10",
    issuedDate: "2026-06-26",
    status: "overdue",
    sequenceStep: 2,
    lastContact: "2026-07-07",
    tone: "firm",
    integration: "quickbooks",
    daysOverdue: 3,
  },
  {
    id: "inv-009",
    number: "INV-2026-0369",
    client: "Priya Sharma",
    company: "Sharma Digital Marketing",
    email: "priya@sharmadigital.com",
    phone: "+1 (408) 555-0956",
    amount: 1650.0,
    dueDate: "2026-07-08",
    issuedDate: "2026-06-24",
    status: "paid",
    sequenceStep: 0,
    lastContact: "2026-07-11",
    tone: "friendly",
    integration: "wave",
    daysOverdue: 0,
  },
  {
    id: "inv-010",
    number: "INV-2026-0418",
    client: "Michael Torres",
    company: "Torres Landscaping",
    email: "mtorres@torreslandscaping.com",
    phone: "+1 (602) 555-1067",
    amount: 2200.0,
    dueDate: "2026-07-12",
    issuedDate: "2026-06-28",
    status: "active",
    sequenceStep: 1,
    lastContact: "2026-07-01",
    tone: "friendly",
    integration: "csv",
    daysOverdue: 1,
  },
];

export const ACTIVITY_FEED: ActivityItem[] = [
  {
    id: "act-1",
    timestamp: "2026-07-12 09:14 AM",
    type: "email",
    message: "Firm notice sent to Elena Rodriguez (INV-2026-0421)",
    invoiceId: "inv-003",
    client: "Elena Rodriguez",
  },
  {
    id: "act-2",
    timestamp: "2026-07-12 08:00 AM",
    type: "sync",
    message: "QuickBooks nightly sync: 3 new unpaid invoices imported",
  },
  {
    id: "act-3",
    timestamp: "2026-07-11 04:32 PM",
    type: "payment",
    message: "Payment detected — sequence stopped for Priya Sharma ($1,650)",
    invoiceId: "inv-009",
    client: "Priya Sharma",
  },
  {
    id: "act-4",
    timestamp: "2026-07-11 10:15 AM",
    type: "sms",
    message: "SMS follow-up sent to Marcus Williams (INV-2026-0398)",
    invoiceId: "inv-002",
    client: "Marcus Williams",
  },
  {
    id: "act-5",
    timestamp: "2026-07-10 09:00 AM",
    type: "email",
    message: "Firm notice sent to Sarah Chen (INV-2026-0412)",
    invoiceId: "inv-001",
    client: "Sarah Chen",
  },
  {
    id: "act-6",
    timestamp: "2026-07-09 08:00 AM",
    type: "sync",
    message: "FreshBooks sync completed — 1 invoice updated",
  },
  {
    id: "act-7",
    timestamp: "2026-07-08 11:22 AM",
    type: "sequence",
    message: "Sequence advanced to Step 2 for Robert Hayes (INV-2026-0440)",
    invoiceId: "inv-008",
    client: "Robert Hayes",
  },
  {
    id: "act-8",
    timestamp: "2026-07-07 03:45 PM",
    type: "email",
    message: "Friendly reminder sent to James Okonkwo (INV-2026-0387)",
    invoiceId: "inv-004",
    client: "James Okonkwo",
  },
  {
    id: "act-9",
    timestamp: "2026-07-06 09:30 AM",
    type: "sequence",
    message: "Lisa Thompson requested pause — sequence halted at Step 2",
    invoiceId: "inv-007",
    client: "Lisa Thompson",
  },
  {
    id: "act-10",
    timestamp: "2026-07-05 08:00 AM",
    type: "sync",
    message: "Wave integration sync: 2 invoices refreshed",
  },
];

export const RECOVERY_DATA: RecoveryMonth[] = [
  { month: "Feb 2026", collected: 4200, attributed: 3100, invoicesRecovered: 3 },
  { month: "Mar 2026", collected: 6800, attributed: 5200, invoicesRecovered: 5 },
  { month: "Apr 2026", collected: 5100, attributed: 4100, invoicesRecovered: 4 },
  { month: "May 2026", collected: 8900, attributed: 7200, invoicesRecovered: 6 },
  { month: "Jun 2026", collected: 11200, attributed: 9400, invoicesRecovered: 8 },
  { month: "Jul 2026", collected: 7650, attributed: 6150, invoicesRecovered: 5 },
];

export const DASHBOARD_STATS = {
  totalOutstanding: 38725.5,
  activeSequences: 8,
  recoveredThisMonth: 6150,
  avgDaysToPayment: 11.4,
  collectionRate: 73,
};

export const TONE_PREVIEWS = {
  friendly: {
    subject: "Quick reminder about Invoice INV-2026-0398",
    body: "Hi Marcus! Hope you're doing well. Just a friendly nudge that invoice INV-2026-0398 for $1,875.50 was due on July 5. Let me know if you have any questions — happy to help!",
  },
  firm: {
    subject: "Past due: Invoice INV-2026-0412 — action required",
    body: "Hi Sarah, Invoice INV-2026-0412 for $4,250.00 is now 15 days past due. Please arrange payment at your earliest convenience. Reply to this email if there's an issue we should discuss.",
  },
  formal: {
    subject: "FINAL NOTICE: Invoice INV-2026-0421 — 12 days overdue",
    body: "Dear Ms. Rodriguez, This is a formal notice regarding Invoice INV-2026-0421 in the amount of $6,200.00, now 12 days past the agreed due date. Failure to remit payment within 7 business days may result in further collection action per our service agreement.",
  },
};

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: amount % 1 === 0 ? 0 : 2,
  }).format(amount);
}

export function formatDate(dateStr: string): string {
  if (dateStr === "—") return "—";
  return new Date(dateStr + "T12:00:00").toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}
